src/pet-care/Controllers/CallsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using PetShopProj.Data;
using PetShopProj.Hubs;
using PetShopProj.Models;

namespace PetShopProj.Controllers
{
    public class CallsController : Controller
    {
        readonly PetDbContext _ctx;
        readonly IHubContext<CallCenterHub, ICallCenterHub> _signalrHub;

        public CallsController(PetDbContext context,
            IHubContext<CallCenterHub, ICallCenterHub> signalrHub)
        {
            _signalrHub = signalrHub;
            _ctx = context;
        }

        // GET: Calls
        public async Task<IActionResult> Index() => View(await _ctx.Calls.ToListAsync());

        [HttpGet]
        public IActionResult GetCalls()
        {
            var res = _ctx.Calls.ToList();
            return Ok(res);
        }

        // GET: Calls/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _ctx.Calls == null)
                return NotFound();

            var call = await _ctx.Calls.FirstOrDefaultAsync(m => m.Id == id);
            if (call == null)
                return NotFound();

            return View(call);
        }

        // GET: Calls/Create

        public IActionResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Email,Problem,CallTime,Answered,AnswerTime")] Call call)
        {
            if (ModelState.IsValid)
            {
                _ctx.Add(call);
                await _ctx.SaveChangesAsync();
                await _signalrHub.Clients.Group("CallCenters").NewCallReceivedAsync(call);
                //await _signalrHub.Clients.All.SendAsync("LoadCalls");
                return RedirectToAction("Index", "Home");
            }
            return BadRequest(); // ❗ hoặc trả lại view lỗi
        }
  

        // GET: Calls/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _ctx.Calls == null)
                return NotFound();

            var call = await _ctx.Calls.FindAsync(id);
            if (call == null)
                return NotFound();

            return View(call);
        }

        // POST: Calls/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,Problem,CallTime,Answered,AnswerTime")] Call call)
        {
            if (id != call.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _ctx.Update(call);
                    await _ctx.SaveChangesAsync();
                    await _signalrHub.Clients.Group("CallCenters").CallEditedAsync(call);
                    //await _signalrHub.Clients.All.SendAsync("LoadCalls");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CallExists(call.Id))
                        return NotFound();
                    else
                        throw;
                }
                return RedirectToAction(nameof(Index));
            }

            return View(call);
        }

        // GET: Calls/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                var call = await _ctx.Calls.Where(c => c.Id == id).FirstOrDefaultAsync();
                if (call == null) return BadRequest();

                _ctx.Calls.Remove(call);
                if (await _ctx.SaveChangesAsync() > 0)
                {
                    await _signalrHub.Clients.Group("CallCenters").CallDeletedAsync();
                    //await _signalrHub.Clients.All.SendAsync("LoadCalls");
                    //return Ok(new { success = true, deletedCall = call });
                    return RedirectToAction(nameof(Index));
                }
                else
                    return BadRequest("Database Error");
            }
            catch
            {
                return StatusCode(500);
            }
        }

        // POST: Calls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_ctx.Calls == null)
                return Problem("Entity set 'PetDbContext.Calls' is null.");
            var call = await _ctx.Calls.FindAsync(id);
            if (call != null)
                _ctx.Calls.Remove(call);

            await _ctx.SaveChangesAsync();
            await _signalrHub.Clients.Group("CallCenters").CallDeletedAsync();
            //await _signalrHub.Clients.All.SendAsync("LoadCalls");
            return RedirectToAction(nameof(Index));
        }

        bool CallExists(int id) => _ctx.Calls.Any(e => e.Id == id);
    }
}

src/pet-care/Views/Shared/_Layout.cshtml
@*@model SearchAnimalViewModel;*@
@inject SignInManager<IdentityUser> signInManager;
@{
    var searchModel = new SearchAnimalViewModel();
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
  
    <link rel="stylesheet" href="@Url.Content("~/lib/bootstrap/css/bootstrap.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/css/StyleSheet.css")" />
    <link rel="stylesheet" href="@Url.Content("~/css/site.css")" />
    <link rel="stylesheet" href="@Url.Content("~/css/style.css")" />
    <link rel="stylesheet" href="@Url.Content("~/css/about.css")" />
    <link rel="stylesheet" href="@Url.Content("~/css/contact.css")" />
    <link rel="stylesheet" href="@Url.Content("~/css/pricing.css")" />
    <link rel="stylesheet" href="@Url.Content("~/css/services.css")" />

    <script src="@Url.Content("~/lib/jquery/jquery.min.js")"></script>
    <script src="@Url.Content("~/lib/jquery-validation/jquery.validate.min.js")"></script>
    <script src="@Url.Content("~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js")"></script>
    <script src="@Url.Content("~/lib/bootstrap/js/bootstrap.bundle.min.js")"></script>
    <script src="@Url.Content("~/js/theme-mode.js")"></script>
       <style>
        .my-dropdown {
            position: relative;
            display: inline-block;
        }

        .my-dropdown-menu {
            position: absolute;
            top: 100%;
            left: 0;
            z-index: 1000;
            display: none;
            min-width: 10rem;
            padding: 0.5rem 0;
            margin: 0.25rem 0 0;
            font-size: 1rem;
            color: #212529;
            text-align: left;
            background-color: #fff;
            border: 1px solid rgba(0, 0, 0, 0.15);
            border-radius: 0.25rem;
            list-style: none;
        }

        .my-dropdown:hover .my-dropdown-menu {
            display: block;
        }

        .my-dropdown1 {
            position: relative;
            display: inline-block;
        }

        .my-dropdown1-menu {
            position: absolute;
            top: 100%;
            left: 0;
            z-index: 1000;
            display: none;
            min-width: 10rem;
            padding: 0.5rem 0;
            margin: 0.25rem 0 0;
            font-size: 1rem;
            color: #212529;
            text-align: left;
            background-color: #fff;
            border: 1px solid rgba(0, 0, 0, 0.15);
            border-radius: 0.25rem;
            list-style: none;
        }

        .my-dropdown1:hover .my-dropdown1-menu {
            display: block;
        }
    </style>
</head>
<body>
    <header class="header">
        <a href="/" class="logo"><i class="fa-solid fa-paw"></i>Pet<span>Care</span></a>
        <nav class="navbar">
              <li>
                <a class="@((ViewBag.Title == "Home") ? "fw-bold" : "")" asp-controller="Home" asp-action="Index">Home</a>
                </li>
            <li class="nav-item">
                <a class="nav-link @((ViewBag.Title is string t && t.Length > 7 && t.Substring(0, 7) == "Services") ? "fw-bold" : "")" asp-controller="Home" asp-action="Categories">Services</a>
            </li>
            <div class="nav-item my-dropdown">
                <a class="nav-link" role="button">Center</a>
                <ul class="my-dropdown-menu">
                 
                    <li><a class="dropdown-item text-dark" asp-controller="Calls" asp-action="Create">Help Center</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                </ul>
            </div>
     
        </nav>
            <nav class="navbar">
                      

                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                <li class="nav-item my-dropdown1">
                                <a class="nav-link" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin
                                </a>
                    <ul class="my-dropdown1-menu">
                        <li><a class="dropdown-item text-dark" asp-controller="Calls" asp-action="Index">Calls</a></li>
                                    <li><a class="dropdown-item text-dark" asp-controller="Home" asp-action="AddAnimal">Add Service</a></li>
                                    <li><a class="dropdown-item text-dark" asp-controller="Home" asp-action="ManageCategories">Manage Categories</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item text-dark" asp-controller="Account" asp-action="ManageUsers">Manage Users</a></li>
                                </ul>
                            </li>
                        }

                        @if (signInManager.IsSignedIn(User))
                        {
                            <li>
                                <form class="" method="post" asp-controller="Account" asp-action="Logout">
                        <button type="submit" class="btn btn-outline-success btn-account">
                                        Logout @User.Identity!.Name
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                  <div>
                @*https://stackoverflow.com/a/4526286/19827098*@
                <form enctype="multipart/form-data" method="post" class="d-flex form-search" asp-controller="Home" asp-action="Search">
                    <span asp-validation-for="@searchModel.Content" class="text-danger"></span>
                    <input name="text" asp-for="@searchModel.Content" class=" form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        
            </nav>
        <i id="menu-btn" class="fas fa-bars"></i>
    </header>


    @{
        var path = Context.Request.Path;
        var isHomeOrCategory = path == "/" || path == "/Home/Categories";
        var containerClass = isHomeOrCategory ? "" : "container";
    }
    <main>
    <div class="@containerClass">
        @*<partial name="_CookieConsentPartial" />*@
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    </main>
    <footer class="footer navbar-fixed-bottom">
         <section class="footer">
        <div class="footer-content">
           <h3><i class="fa-solid fa-paw"></i>Pet<span>Care</span></h3> 
           <p>PetCare is a pet caring shop, where we provide facilites and various useful treatments. We offer Massage, a good ground, expert staff, good facilites and much more! Visit us anytime :). We are closed only on thrusday and our regular timings are 9:00AM to 10:00PM.</p>
           <ul class="socials">
            <li><a href=”#”><i class="fa fa-facebook"></i></a></li>
            <li><a href=”#”><i class="fa fa-twitter"></i></a></li>
            <li><a href=”#”><i class="fa-brands fa-google-plus-g"></i></a></li>
            <li><a href=”#”><i class="fa fa-youtube"></i></a></li>
            <li><a href=”#”><i class="fa fa-linkedin-square"></i></a></li>
         </ul>
        </div>
    </section>
    <section class="footer-bottom">
       <p style="margin-bottom:0px">copyright &copy;2025 <a href=”#”>Ver Sama</a> - Pet Care </p>
    </section>
    </footer>

    <environment include="Development">
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    asp-fallback-src="~/lib/jquery/jquery.min.js"
    asp-fallback-test="window.jQuery"
    crossorigin="anonymous"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
    asp-fallback-src="~/lib/bootstrap/js/bootstrap.bundle.min.js"
    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
    crossorigin="anonymous"
    integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
    </script>
    </environment>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/signalr/signalr.js"></script>
    <script src="~/lib/moment/min/moment.min.js"></script>
    <script>
                let menu = document.querySelector("#menu-btn");
        let navbar = document.querySelector(".navbar");

        menu.onclick = () => {
          menu.classList.toggle("fa-times");
          navbar.classList.toggle("active");
        };

        window.onscroll = () => {
          menu.classList.remove("fa-times");
          navbar.classList.remove("active");
        };

        window.addEventListener("scroll", function () {
          const nav = document.querySelector("header");
          nav.classList.toggle("sticky", window.scrollY)});
    </script>
     <script src="https://kit.fontawesome.com/cb8535f973.js" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/pet-care/Views/Shared/_PartialView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}